### ISSUE TITLE
Request: Please update to support Nextcloud 22.1.0

### ISSUE THREAD

**Issue by KruyKaze** [marcelklehr/recognize#45]
Hello,
I updated NC and now Recognize is no longer supported.
Hopefully it's an easy fix.
Thank you!

**Comment by isaacolsen94** [comment]
Also running 22.1.0 and I'm having issues. A new install however so I can't say if it was working before. But support for the latest install would be awesome! Thank you!

**Comment by bonswouar** [comment]
It's already been changed [in a previous commit](https://github.com/marcelklehr/recognize/commit/92afb51b2028bdf2b7812bf7c44e166b63b7365f#diff-ab97a56738913a50d2334c4d3f10991748d3e29d011f5a674734b63d33d5ce9e), it should be ok when release will be ready (hopefully soon!).
Meanwhile latest package should still work if you install it manually, doesn't it just appear as "untested apps" in Apps list anyway?

**Comment by isaacolsen94** [comment]
I'm new to Nextcloud so I just did a brand new install of version 22.1.0 and installed Recognize. From the settings page it tells me I have 0 of 0 pictures ready to go. I ran the command manually and I get this error: 
`Running array (
  0 => '/config/www/nextcloud/apps/recognize/bin/node-v14.9.0-linux-x64',
  1 => '/config/www/nextcloud/apps/recognize/src/classifier.js',
  2 => '/data/iolsen/files/Photos/Isaacs Phone - Test/2020-04-13 08.19.34.jpg',
  3 => '/data/iolsen/files/Photos/Isaacs Phone - Test/2020-04-13 08.19.35.jpg',
  4 => '/data/iolsen/files/Photos/Isaacs Phone - Test/2020-04-13 08.19.36.jpg',
  5 => '/data/iolsen/files/Photos/Isaacs Phone - Test/2020-04-13 08.19.37.jpg',
  6 => '/data/iolsen/files/Photos/Isaacs Phone - Test/2020-04-13 08.19.38.jpg',
  7 => '/data/iolsen/files/Photos/Isaacs Phone - Test/2020-04-13 08.19.42.jpg',
  8 => '/data/iolsen/files/Photos/Isaacs Phone - Test/2020-04-13 08.19.43.jpg',
  9 => '/data/iolsen/files/Photos/Isaacs Phone - Test/2020-04-16 20.48.54-1.jpg',
  10 => '/data/iolsen/files/Photos/Isaacs Phone - Test/2020-04-16 20.48.54.jpg',
  11 => '/data/iolsen/files/Photos/Isaacs Phone - Test/2020-04-16 20.48.57-1.jpg',
  12 => '/data/iolsen/files/Photos/Isaacs Phone - Test/2020-04-16 20.48.57.jpg',
)

Classifier process output: sh: exec: line 1: /config/www/nextcloud/apps/recognize/bin/node-v14.9.0-linux-x64: not found

Classifier process output: sh: exec: line 1: /config/www/nextcloud/apps/recognize/bin/node-v14.9.0-linux-x64: not found`

So I checked for said file: 
![image](https://user-images.githubusercontent.com/52682311/129045575-0a12fc80-9fbf-4a35-a23b-1d45d8f69b82.png)

I assumed it was because of 22.1.0 incompatibility, is it actually something else?

**Comment by bonswouar** [comment]
@isaacolsen94 Weird, but it seems to be unrelated to NC 22.
Could you try running the nodejs command yourself?
`/config/www/nextcloud/apps/recognize/bin/node-v14.9.0-linux-x64 '/config/www/nextcloud/apps/recognize/src/classifier.js' '/data/iolsen/files/Photos/Isaacs Phone - Test/2020-04-13 08.19.34.jpg'`

**Comment by isaacolsen94** [comment]
> @isaacolsen94 Weird, but it seems to be unrelated to NC 22.
> Could you try running the nodejs command yourself?
> `/config/www/nextcloud/apps/recognize/bin/node-v14.9.0-linux-x64 '/config/www/nextcloud/apps/recognize/src/classifier.js' '/data/iolsen/files/Photos/Isaacs Phone - Test/2020-04-13 08.19.34.jpg'`

How would one do this? Sorry not very familiar with nodejs

**Comment by bonswouar** [comment]
> How would one do this? Sorry not very familiar with nodejs

@isaacolsen94 I mean, just execute it, this is the command, nodejs binary is the first part (`/config/www/nextcloud/apps/recognize/bin/node-v14.9.0-linux-x64`)
If it exists I don't see why you'd have this error

**Comment by isaacolsen94** [comment]
![image](https://user-images.githubusercontent.com/52682311/129105668-bc2d3612-01a6-482f-bc80-34e580e7395c.png)

**Comment by bonswouar** [comment]
@isaacolsen94 you forgot the `./` in `./node-v14.9.0-linux-x64` needed when executing in current folder (you're server is not on Windows, I hope :smile: )
From there the full command would be : `./node-v14.9.0-linux-x64 '/config/www/nextcloud/apps/recognize/src/classifier.js' '/data/iolsen/files/Photos/Isaacs Phone - Test/2020-04-13 08.19.34.jpg'`

**Comment by isaacolsen94** [comment]
![image](https://user-images.githubusercontent.com/52682311/129106676-eb72a7cc-7c82-4368-9833-9bcf49a7dd02.png)

I thought it might be a permissions error so changed node-v14* to 777 and still unable to find it

**Comment by bonswouar** [comment]
Hm I'm lost haha.
What OS is your server running on?
Yeah I thought about permissions, but you should have a permission error then... Plus right now you're testing as root

**Comment by isaacolsen94** [comment]
I'm running Unraid 6.9.2. And my user inside Nextcloud is 'iolsen' but I tried both and got this: 
![image](https://user-images.githubusercontent.com/52682311/129107758-562cb5aa-cd9d-4939-aec1-bc22ed8f141a.png)

**Comment by bonswouar** [comment]
Unfortunately I don't know much about Unraid, are you executing it from nextcloud docker's console right now?

**Comment by bonswouar** [comment]
> I can paste the entire output of the command if that will help?

No need, the weird thing is that it can execute `occ` command and not node binary.. But I guess it just needs to be able to execute php for that.
There wouldn't be some execution protection or something on your volume/config/something? Maybe you should ask Unraid community (or wait to see if someone here might be able to help more)

**Comment by bonswouar** [comment]
@KruyKaze sorry we kinda hijacked your thread ;)
Does my first message answer to your problem or you have another issue?

**Comment by KruyKaze** [comment]
No worries, I'm waiting for next release anyway to fix the maxarg issue so
I can test .

**Comment by marcelklehr** [comment]
@isaacolsen94 see https://github.com/marcelklehr/recognize/issues/16

**Comment by marcelklehr** [comment]
v22 support is fixed in master, next release will support v22.
